### ISSUE TITLE
反馈：1.0新版本闪退

### ISSUE THREAD

**Issue by dateszb** [zodiac182/fxxkxuexi#17]
用新的1.0版本，无论是用户名还是扫码登录后，从分数界面跳转到浏览文章时，浏览器和cmd窗口就会闪退，主程序提示“当日学习任务未完成，但爬取的文章已全部阅读完毕”。实际上只拿了登录的1分。转回用之前的0.1.1版没有问题。系统win10 1809。
最后再次感谢辛勤劳动！希望只是个例

**Comment by zodova** [comment]
fixed
