### ISSUE TITLE
点赞

### ISSUE THREAD

**Issue by apgk** [zodiac182/fxxkxuexi#2]
感谢作者。

**Comment by noway2014** [comment]
请问下载的放在哪个drive文件夹？具体路径是？浏览器版本有要求吗

**Comment by apgk** [comment]
> 请问下载的放在哪个驱动文件夹？具体路径是？浏览器版本有要求吗

你chrome版本是什么，就去下载对应的chromedriver.exe，替换掉driver文件下的chromedriver.exe
[编译版下载地址](https://github.com/zodiac182/autoxuexi/raw/2dd008da569206797fcb355835eb1b963e01b502/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.rar )

**Comment by noway2014** [comment]
谢谢楼上，是不是http://chromedriver.storage.googleapis.com/index.html这里下载并替换自己chorme浏览器的？另外文中哪个drives文件夹，是指win系统的，还是chorme浏览器安装文件夹的？

**Comment by apgk** [comment]
> 谢谢楼上，是不是[http://chromedriver.storage.googleapis.com/index.html这里下载并替换自己chorme浏览器的？另外文中哪个drives文件夹，是指win系统的，还是chorme浏览器安装文件夹的？](http://chromedriver.storage.googleapis.com/index.html%E8%BF%99%E9%87%8C%E4%B8%8B%E8%BD%BD%E5%B9%B6%E6%9B%BF%E6%8D%A2%E8%87%AA%E5%B7%B1chorme%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%EF%BC%9F%E5%8F%A6%E5%A4%96%E6%96%87%E4%B8%AD%E5%93%AA%E4%B8%AAdrives%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%8C%E6%98%AF%E6%8C%87win%E7%B3%BB%E7%BB%9F%E7%9A%84%EF%BC%8C%E8%BF%98%E6%98%AFchorme%E6%B5%8F%E8%A7%88%E5%99%A8%E5%AE%89%E8%A3%85%E6%96%87%E4%BB%B6%E5%A4%B9%E7%9A%84%EF%BC%9F)
你下载我链接中的编译版本就知道了，解压完就有这个对应文件夹，还有驱动就是这个网址下载的

**Comment by noway2014** [comment]
非常感谢…

**Comment by noway2014** [comment]
测试了，你的连接下载的编译版本提示跟系统不兼容，能否给一个win7 32
位的版本。谢谢
