### ISSUE TITLE
参考一下，隐藏页面

### ISSUE THREAD

**Issue by sygdtv** [zodiac182/fxxkxuexi#25]
广告链接，已删除

def _login(self):
        chrome_options = webdriver.ChromeOptions()
        if self.config["chrome_mute"]:
            chrome_options.add_argument('--mute-audio')  # 关闭声音
        if self.config["hide_page"]:
            chrome_options.add_argument("--headless")  # 隐藏页面
        chrome_driver = self.config["chrome_driver"]  # chromedriver的路径
        # 实例化浏览器
        driver = webdriver.Chrome(executable_path=chrome_driver, chrome_options=chrome_options)
        driver.maximize_window()

**Comment by zodova** [comment]
瞎？
