### ISSUE TITLE
反馈：1.1.1版本视频学习异常

### ISSUE THREAD

**Issue by JoeZhangYN** [zodiac182/fxxkxuexi#26]
系统版本:Vmware15.0.4，winserver 2019 1809。
文章学习没问题，
视频跳转没问题。
但视频跳转后获取不到视频的信息和时长，
然后反复跳到积分获取界面，再跳回视频。学习进度不变。

**Comment by dateszb** [comment]
我碰到的问题是视频页面经常不会自动播放，计算不了视频观看时长，最近发生的比较频繁，从1.1到1.1.1都有这样的情况

**Comment by zodova** [comment]
嗯，找到原因了，视频还没有加载成功，获取到的播放时间是00：00， 就直接找下一个去了。
已经更新了 请下载1.1.2

**Comment by JoeZhangYN** [comment]
更新1.1.2版本后，测试正常。
