### ISSUE TITLE
用python3.X运行发现的问题

### ISSUE THREAD

**Issue by iloverbr** [zodiac182/fxxkxuexi#5]
1迭代器中的.next（）方法，在python3中要么写出__next__  ; 要么写为next(迭代器)
2python 3中print要加（）,作者有一句话没有加
3Tkinter要改为tkinter
4tkMessagebox导入的那句话要改为from tkinter import messagebox
5（未解决，求作者解答）：代码第65行：        list_a = iter(os.listdir('articles/'))  系统一直提示早不到这个文件

**Comment by zodova** [comment]
5.  确保目录 videos 和 articles存在
